### ISSUE TITLE
Not extracting the right feature

### ISSUE THREAD

**Issue by LuisTbx** [jacobgil/CaffeFeaturesExample#1]
Hi,

I was having a look to your code, it seems that you are always extracting the information from the net, and you never touch the image itself. In order to fix it, you may have to reshape the layer called "data" from the network, then pre-process the image and set it as your data layer. Then compute a forward pass, and then extract the features.

something like this:

in_net.blobs['data'].reshape(1,3,227,227)  # first reshape the data layer to be same size as the input image, i do it in the initialize net.

def get_feature(current_file, in_net, in_transformer):
    in_net.blobs['data'].data[...] = in_transformer.preprocess('data', caffe.io.load_image(current_file)) # set image to be the data layer. 
    out = in_net.forward(['fc7']) # compute forward pass to obtain the new feature
    feat = out['fc7'] # extract feature you need, in my case i want to use FC7
    return feat

Cheers, hope it helps.

**Comment by jacobgil** [comment]
Thanks, I appreciate it!
When I get back to a machine with Caffe installed I'l fix it.

**Comment by LuisTbx** [comment]
Hi,
I also found that using lambdas and maps can be an issue, since caffe is returning data from a C++ pointers. So, what? well, in python you are not the owner of this pointer and using a pointer who's being modified in the C side will lead to have always the same feature.

My proposal, use the old friend the for loop and pre-allocate your matrix that will hold the features. Or, return a copy of the fc7 features and keep the lambdas (that may help, but did not test it).

Cheers,
